# Name of the workflow
name: scrape-detik

# digunakan untuk workflows triggered by push
on:
  push:
    branches: main

# digunakan untuk workflows by scheduled
#on:
#  schedule:
#    - cron: "*/5 * * * *" # every 5 minutes

# Jobs - What the computer should do? 
jobs:
  import-data:
    # kita buat github action berjalan di ubuntu versi terbaru
    runs-on: ubuntu-latest
    steps:
      # langkah pertama install R
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
      
      # langkah kedua kita update dan install library di ubuntu
      - run: |
          sudo apt-get update
          # khusus rvest di R, dibutuhkan libraries ubuntu sebagai berikut:
          sudo apt-get install libcurl4-openssl-dev
          
      # berikutnya adalah install libraries yang dibutuhkan di R
      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::dplyr
            any::rvest
      
      # set working directory
      - name: Check out repository
        uses: actions/checkout@v3

      # kita buat github action menjalankan skrip scrape.R
      - name: Run skrip R
        run: Rscript -e 'source("Scraper.R")'
      
      # berikutnya kita akan commit dan push ke repo
      - name: Commit results
        run: |
          git config --local user.email "ikanx101@gmail.com"
          git config --local user.name "ikanx101"
          git add .
          git commit -m 'Data updated' || echo "No changes to commit"
          git push || echo "No changes to commit"
          # jangan lupa set permission dulu ya
